//! Fixture gate for the hallucination audit (whisper-hallucination-cleanup
//! tasks 1.3 / 5.1).
//!
//! Compares the audit's flagged row ids against the tracked
//! `tests/expected-flags.json` (generated by
//! `openspec/exploration/hallucination-detector-probe.py --expectations`),
//! keyed by each fixture's `row_sha256` so a re-pinned snapshot fails loudly
//! instead of silently passing. The transcript fixtures themselves are
//! untracked by policy; when they are absent the test skips with a notice.

use app_lib::audio::hallucination::audit;
use std::collections::BTreeSet;

fn fixture_path(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

#[test]
fn audit_matches_tracked_expectations_on_both_fixtures() {
    let expectations_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/expected-flags.json");
    let raw = std::fs::read_to_string(&expectations_path)
        .expect("tests/expected-flags.json must be present (it is tracked)");
    let expectations: serde_json::Value = serde_json::from_str(&raw).unwrap();

    assert!(
        expectations.as_object().unwrap().len() >= 2,
        "expectations must cover both cde5c264 fixtures"
    );

    for (row_sha, entry) in expectations.as_object().unwrap() {
        let fixture = entry["fixture"].as_str().unwrap();
        let path = fixture_path(fixture);
        if !path.exists() {
            println!(
                "SKIP {fixture}: untracked fixture absent — copy it into tests/fixtures/ to run the gate"
            );
            continue;
        }

        let raw = std::fs::read_to_string(&path).unwrap();
        let doc: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(
            doc["row_sha256"].as_str().unwrap(),
            row_sha,
            "{fixture} drifted from the pinned snapshot — regenerate tests/expected-flags.json \
             via hallucination-detector-probe.py --expectations after re-pinning"
        );

        let rows = doc["rows"].as_array().unwrap();
        assert_eq!(
            rows.len() as u64,
            entry["rows_total"].as_u64().unwrap(),
            "{fixture} row count changed without a re-pin"
        );

        let expected: BTreeSet<&str> = entry["flagged"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| f["id"].as_str().unwrap())
            .collect();
        let flagged: BTreeSet<&str> = rows
            .iter()
            .filter(|r| {
                audit(
                    r["text"].as_str().unwrap(),
                    r["start_ms"].as_f64().unwrap(),
                    r["end_ms"].as_f64().unwrap(),
                )
                .is_garbage
            })
            .map(|r| r["id"].as_str().unwrap())
            .collect();

        let missed: Vec<_> = expected.difference(&flagged).collect();
        let damaged: Vec<_> = flagged.difference(&expected).collect();
        assert!(
            missed.is_empty(),
            "{fixture}: audit missed garbage rows {missed:?}"
        );
        assert!(
            damaged.is_empty(),
            "{fixture}: audit flagged clean rows {damaged:?}"
        );
        println!("{fixture}: {}/{} flagged rows match expectations", flagged.len(), rows.len());
    }
}
